/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.panel;

import src.crepemaker.CrepeCaseTrabalhado;
import src.crepemaker.CrepeMaker;

/**
 *
 * @author arthur
 */
public class MainScreen extends javax.swing.JFrame {
    private CrepeMaker crepeMaker;
    private CrepeScreen crepeScreen;
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        this.crepeMaker = new CrepeMaker();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonFrango = new javax.swing.JButton();
        buttonChocolate = new javax.swing.JButton();
        buttonMorango = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        buttonFrango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/frango.png"))); // NOI18N
        buttonFrango.setText("frango");
        buttonFrango.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonFrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFrangoActionPerformed(evt);
            }
        });

        buttonChocolate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/chocolate.png"))); // NOI18N
        buttonChocolate.setText("chocolate");
        buttonChocolate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChocolateActionPerformed(evt);
            }
        });

        buttonMorango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/morango.png"))); // NOI18N
        buttonMorango.setText("morango");
        buttonMorango.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonMorango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMorangoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonChocolate, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(buttonFrango, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMorango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonFrango)
                .addGap(60, 60, 60)
                .addComponent(buttonChocolate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(buttonMorango)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFrangoActionPerformed
       this.crepeScreen = new CrepeScreen(this.crepeMaker, CrepeCaseTrabalhado.CREPEIRAUM);
       this.crepeScreen.setMainScreen(this);
       this.crepeScreen.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_buttonFrangoActionPerformed

    private void buttonChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChocolateActionPerformed
        this.crepeScreen = new CrepeScreen(this.crepeMaker, CrepeCaseTrabalhado.CREPEIRADOIS);
        this.crepeScreen.setMainScreen(this);
        this.crepeScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonChocolateActionPerformed

    private void buttonMorangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMorangoActionPerformed
        this.crepeScreen = new CrepeScreen(this.crepeMaker, CrepeCaseTrabalhado.CREPEIRATRES);
        this.crepeScreen.setMainScreen(this);
        this.crepeScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonMorangoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChocolate;
    private javax.swing.JButton buttonFrango;
    private javax.swing.JButton buttonMorango;
    // End of variables declaration//GEN-END:variables
}
